radio:
  image: natansilva/gfgradio
  container_name: radio
  ports:
    - "80:80"
    - "8080:8080"
  volumes:
    - ../:/var/www/
    - ~/Music/:/var/www/music/
    - ./nginx/:/etc/nginx/sites-enable/
    - ./supervisor/:/etc/supervisor/conf.d/
